---
title: "Promoter_2nd"
author: "Georgii"
date: "11 04 2021"
output: html_document
---

```{r}
no <- c(1)
team_name <- c("Jilin_China")
project <- c("iGAME")
                
year <- c(2020) 
                  
wiki <- c("https://2020.igem.org/Team:Jilin_China")
 

igem_team <- data.frame(no, 
                        team_name, 
                        project, 
                        year, 
                        wiki)
#knitr::kable(std, format = "markdown")
knitr::kable(igem_team)

```

```{r}
id <- 1:4
BBid <- c("BBa_I0500", 
             "BBa_B0034",
             "BBa_K2541400",
             "BBa_B0015")
type <- c("Promoter", "RBS", "RFP", "Terminator")
link <- c("http://parts.igem.org/Part:BBa_I0500",
           "http://parts.igem.org/Part:BBa_B0034",
           "http://parts.igem.org/Part:BBa_K2541400",
           "http://parts.igem.org/Part:BBa_B0015")
backbone <- rep("-", length(id))
device_id <- paste0("D", sprintf("%04d", rep(1, length(id))) )
team_name <- rep("Jilin_China", length(id))
user <- rep("gpemelianov", length(id))

igem_part <- data.frame(id, BBid, type, link, backbone, device_id, team_name, user)
#knitr::kable(igem_part)
igem_part
```
```{r}
id <- c(1:3)
strain <- rep("E.coli", length(id))
indc <- rep("Arabinose", length(id))
conc <- c(0.02, 0.20, 2.00)
value <- c(3000, 8200, 8000)
valunit <- rep("Fluorescence", length(id))
incubhr <- rep(12, length(id))
incubtemp <- rep("-", length(id))
device_id <- rep("D0001", length(id))
link <- rep("https://2020.igem.org/Team:Jilin_China/Proof_Of_Concept", length (id))

igem_obs <- data.frame(id, strain, indc, conc, value,
                        valunit, incubhr, incubtemp,
                       device_id, link)
#knitr::kable(igem_obs)
igem_obs
```

```{r}
library(tidyverse)
```
```{r}
igem_promoter <- igem_part %>% 
  left_join(igem_team, by="team_name") %>% 
  left_join(igem_obs, by="device_id")
  
igem_promoter
```
```{r}
colnames(igem_promoter)
```

```{r}
plot_data <- igem_promoter %>% 
  filter(BBid=="BBa_I0050") %>% 
  select(incubhr, conc, value) %>% 
  mutate(incubhr=factor(incubhr), conc=factor(conc))
plot_data
```
```{r}
ggplot(plot_data, aes(x=incubhr, y=value, fill=conc)) +
  geom_bar(stat="identity", position=position_dodge(width=0.5), width=0.4) +
  scale_fill_manual(values=c("#ce1212", "#4a47a3")) +
  theme_bw()
```

