---
title: "Promoter_3rd"
author: "Georgii"
date: "11 04 2021"
output: html_document
---

```{r}
igem_team <-data.frame (id="1",
                        team_name = "BHSF_ND",
                        project = "Protector a bistable system",
                        year = "2019",
                        wiki = "https://2019.igem.org/Team:BHSF_ND")
```

```{r}
igem_part <- data.frame(id = 1:2,
                        BBid = c("BBa_I0500",
                                 "BBa_K3202022"),
                        type = c("Promoter", 
                                 "msfGFP"),
                        link = c("http://parts.igem.org/Part:BBa_I0500",
           "http://parts.igem.org/Part:BBa_K3202022"),
                        backbone = rep("pSC101", 2),
                        device_id = paste0("D", sprintf("%04d", rep(1, 2))),
                        team_name = rep("BHSF_ND", 2),
                        user = rep("gpemelianov", 2))
igem_part
```
```{r}
igem_obs <- data.frame(id = 1:7,
             strain = rep("E. coli", length(7)),
             indc = rep("Ara", length(7)),
             conc = c(0, 0.001, 0.005, 0.01, 0.05, 0.1, 1),
             concunit = rep("mM", length(7)),
             value = c(250, 500, 600, 750, 2000, 5000, 10000),
             valunit = c("a.u."),
             incubhr = rep(4, length(7)),
             incubtemp = rep(37, length(7)),
             device_id = paste0("D", sprintf("%04d", 1)),
             link = c("https://2019.igem.org/Team:BHSF_ND/Project/Leakage#ct3"))
igem_obs
```



```{r}
library(tidyverse)
id <- c(1)
team_name <- c("Jilin_China")
project <- c("iGAME")
                
year <- c("2020") 
                  
wiki <- c("https://2020.igem.org/Team:Jilin_China")
 

igem_team1 <- data.frame(id, 
                        team_name, 
                        project, 
                        year, 
                        wiki)
igem_team2 <-data.frame (id= 1,
                        team_name = "BHSF_ND",
                        project = "Protector a bistable system",
                        year = "2019",
                        wiki = "https://2019.igem.org/Team:BHSF_ND")
# error
#bind_rows(igem_team1, igem_team2)

id <- c(1)
team_name <- c("Jilin_China")
project <- c("iGAME")
year <- c("2020")
wiki <- c("https://2020.igem.org/Team:Jilin_China")

igem_team1 <- data.frame(id,
                         team_name,
                         project,
                         year,
                         wiki)

bind_rows(igem_team1, igem_team2)

```
```{r}
#igem_part
id <- 1:2
                        BBid <- c("BBa_I0500",
                                 "BBa_K3202022")
                        type <- c("Promoter", 
                                 "msfGFP")
                        link <- c("http://parts.igem.org/Part:BBa_I0500",
           "http://parts.igem.org/Part:BBa_K3202022")
                        backbone <- rep("pSC101", 2)
                        device_id <- paste0("D", sprintf("%04d", rep(1, 2)))
                        team_name <- rep("BHSF_ND", 2)
                        user <- rep("gpemelianov", 2)
igem_part1 <- data.frame(id, BBid, type, link, backbone, device_id, team_name, user)

id <- 1:4
BBid <- c("BBa_I0500", 
             "BBa_B0034",
             "BBa_K2541400",
             "BBa_B0015")
type <- c("Promoter", "RBS", "RFP", "Terminator")
link <- c("http://parts.igem.org/Part:BBa_I0500",
           "http://parts.igem.org/Part:BBa_B0034",
           "http://parts.igem.org/Part:BBa_K2541400",
           "http://parts.igem.org/Part:BBa_B0015")
backbone <- rep("-", length(id))
device_id <- paste0("D", sprintf("%04d", rep(1, length(id))) )
team_name <- rep("Jilin_China", length(id))
user <- rep("gpemelianov", length(id))

igem_part2 <- data.frame(id, BBid, type, link, backbone, device_id, team_name, user)

igem_part <-bind_rows(igem_part1, igem_part2, .id="id")
igem_part
```


```{r}
id <- c(1:3)
strain <- rep("E.coli", length(3))
indc <- rep("Arabinose", length(3))
conc <- c(0.02, 0.20, 2.00)
concunit <- rep("mM", length(id))
value <- c(3000, 8200, 8000)
valunit <- rep("Fluorescence", length(3))
incubhr <- rep(12, length(3))
incubtemp <- rep(NA, length(3))
device_id <- rep("D0001", length(id))
link <- rep("https://2020.igem.org/Team:Jilin_China/Proof_Of_Concept", length (id))

igem_obs1 <- data.frame(id, strain, indc, conc, concunit, value,
                        valunit, incubhr, incubtemp,
                       device_id, link)

igem_obs2 <- data.frame(id = c(1:7),
             strain = rep("E. coli", length(7)),
             indc = rep("Arabinose",length(7)),
             conc = c(0, 0.001, 0.005, 0.01, 0.05, 0.1, 1),
             concunit = rep("mM", length(7)),
             value = c(250, 500, 600, 750, 2000, 5000, 10000),
             valunit = rep("a.u.", length(7)),
             incubhr = rep(4, length(7)),
             incubtemp = rep(37, length(7)),
             device_id = rep("D0001", length(7)),
             link = rep("https://2019.igem.org/Team:BHSF_ND/Project/Leakage#ct3", length(7)))

igem_obs <- bind_rows(igem_obs1, igem_obs2, .id="id")
igem_obs
```





















